# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)
# Application configuration that is needed by the main controller.
# All information that is specifically for each application should go into `application-spec`.

name:
data-handler:
instance-number: # How many instances you want to create
keep-alive: FALSE
timeout: beamlime.config.preset_options.DEFAULT_TIMEOUT  # 60 s
wait-interval: beamlime.config.preset_options.DEFAULT_WAIT_INTERVAL  # 1 s
