# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)
# @author Sunyoung Yoo
#
# Dependencies on other templates: data-stream-application.yaml,
#                                  workflow.yaml
#                                  target.yaml

general:
  user:
  name:
  last-updated:
  log-dir: # ~/.beamlime/log
  max-paused: beamlime.config.preset_options.DEFAULT_PAUSED  # 60 s

data-stream:
  custom-handler-dir: # ~/.beamlime/custom-handler
  applications:
    # - name: application-name-1
    #   ...
    # - name: application-name-2
    #   ...
    # - name: application-name-3
    #   ...
  application-specs:  # Specs for each applications. It will be passed into the constructor of the handler.
    # application-name-1:
    #  ...
    # applicatoin-name-2:
    #  ...
  communication-channels: # Each channel will be assigned to each application in the application-subscriptions.
    # - name: channel-name-1
    #   type:
    #   options:
    # - name: channel-name-2
    #   type:
    #   options:
    # ...
  application-subscriptions: # Define communication between applications here.
    # - app-name: application-name-1
    #   input-channels:
    #    - channel-name-1
    #   output-channels:
    #    - channel-name-2
    # - app-name: application-name-2
    #   input-channels:
    #    ...
    #   output-channels:
    #    - channel-name-1
    # ...

data-reduction: # Each workflow will be run asynchronously but in one process.
                # Can be split into multi-processes by the data-reduction-manager instance if needed.
  targets:
    # - name: target-name-1
    #   index: ''
    # - name: target-name-2
    #   index: geometry
  workflows:
    # - name: workflow-name-1
    #   ...
