# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)
# @author Sunyoung Yoo
#
# Dependencies on other templates: data-stream-application.yaml,
#                                  data-stream-mapping.yaml,
#                                  workflow.yaml
#                                  target.yaml

general:
  user:
  name:
  last-updated:
  log-dir: beamlime.config.preset_options.DEFAULT_LOG_DIR

dashboard:
  update-frequency: 5 # [Hz]

data-stream:
  custom-handler-dir: beamlime.config.preset_options.DEFAULT_CUSTOM_HANDLER_DIR
  applications: # Each application will be run in different process if possible.
    # - name: application-name-1
    #   ...
    # - name: application-name-2
    #   ...
    # - name: application-name-3
    #   ...
  application-mapping: # Define communication between applications here.
    # - from: application-name-1
    #   to:
    #       - application-name-2
    #       - application-name-3
  application-specs:  # Specs for each applications. It will be passed into the constructor of the handler.
    # application-name-1:
    #  ...
    # applicatoin-name-2:
    #  ...


data-reduction: # Each workflow will be run asynchronously but in one process.
                # Can be split into multi-processes by the data-reduction-manager instance if needed.
  targets:
    # - name: target-name-1
    #   index: ''
    # - name: target-name-2
    #   index: geometry
  workflows:
    # - name: workflow-name-1
    #   ...
