# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)
# Application configuration that is needed by the main controller.
# All information that is specifically for each application should go into `application-spec`.

name:
data-handler:
input-channel: beamlime.config.preset_options.CommunicationChannelOptions
output-channel: beamlime.config.preset_options.CommunicationChannelOptions
keep-alive: FALSE
