# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)
# Data reduction workflow configuration template

name:
reference:
process:
input-policy: REPLACE # SKIP|STACK|APPEND|REPLACE|AVERAGE
output-policy: REPLACE # SKIP|STACK|APPEND|REPLACE|AGERAVE
process-args:
  # - arg1
  # - arg2
process-kwargs:
  # kwarg1: value1
  # kwarg2: value2
  # ...
