# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)
# Data reduction workflow configuration template

name:
reference:
process:
input-policy: beamlime.config.preset_options.NewDataPolicyOptions
output-policy: beamlime.config.preset_options.NewDataPolicyOptions
targets:
  # - target-name-1
  # - target-name-2
process-args:
  # - arg1
  # - arg2
process-kwargs:
  # kwarg1: value1
  # kwarg2: value2
  # ...
